include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Adicionar regras específicas
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_locals: true
    unnecessary_const: true
    unnecessary_new: true
    use_key_in_widget_constructors: true
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
