name: dseven_flutter_app
description: Flutter web app com Clean Architecture e MVVM
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # HTTP Client
  http: ^1.1.0
  
  # JSON Serialization
  json_annotation: ^4.9.0
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Connectivity
  connectivity_plus: ^5.0.2
  
  # Shared Preferences
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/icons/
